/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QXOEMLX3tdR
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from 'next/link'
import {
    CardTitle,
    CardDescription,
    CardHeader,
    CardContent,
    CardFooter,
    Card,
} from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'

export function Component() {
    return (
        <div className="flex min-h-[100dvh] flex-col items-center justify-center bg-gray-100 px-4 py-12 dark:bg-gray-950">
            <div className="mx-auto w-full max-w-md space-y-8">
                <div className="flex items-center justify-center">
                    <Link className="inline-flex items-center gap-2" href="#">
                        <MountainIcon className="h-8 w-8" />
                        <span className="text-2xl font-bold">Acme Inc</span>
                    </Link>
                </div>
                <Card>
                    <CardHeader className="space-y-1">
                        <CardTitle className="text-2xl">
                            Sign in to your account
                        </CardTitle>
                        <CardDescription>
                            Enter your email and password below to access your
                            account.
                        </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className="grid gap-2">
                            <Label htmlFor="email">Email</Label>
                            <Input
                                id="email"
                                placeholder="m@example.com"
                                type="email"
                            />
                        </div>
                        <div className="grid gap-2">
                            <div className="flex items-center justify-between">
                                <Label htmlFor="password">Password</Label>
                                <Link
                                    className="text-sm font-medium underline underline-offset-4 hover:text-gray-900 dark:hover:text-gray-50"
                                    href="#"
                                >
                                    Forgot password?
                                </Link>
                            </div>
                            <Input id="password" type="password" />
                        </div>
                    </CardContent>
                    <CardFooter>
                        <Button className="w-full" type="submit">
                            Sign in
                        </Button>
                    </CardFooter>
                </Card>
            </div>
        </div>
    )
}

function MountainIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
        </svg>
    )
}
