/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wJ90T1c4nEQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function wishlistpage() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="grid gap-8">
          <div className="grid gap-2">
            <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">My Wishlist</h1>
            <p className="text-gray-500 dark:text-gray-400">These are the items I'd like to purchase.</p>
          </div>
          <ul className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4" />
        </div>
      </div>
    </section>
  )
}
